exports.up = (pgm) => {
  pgm.sql(`
    CREATE FUNCTION app_set_updated_at()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      NEW.updated_at = CURRENT_TIMESTAMP;
      RETURN NEW;
    END;
    $$;

    CREATE FUNCTION app_day_name_to_number(day_name text)
    RETURNS integer
    LANGUAGE sql
    IMMUTABLE
    AS $$
      SELECT CASE LOWER(day_name)
        WHEN 'monday' THEN 1
        WHEN 'tuesday' THEN 2
        WHEN 'wednesday' THEN 3
        WHEN 'thursday' THEN 4
        WHEN 'friday' THEN 5
        WHEN 'saturday' THEN 6
        WHEN 'sunday' THEN 7
        ELSE NULL
      END
    $$;

    CREATE FUNCTION app_day_number_to_name(day_number integer)
    RETURNS text
    LANGUAGE sql
    IMMUTABLE
    AS $$
      SELECT CASE day_number
        WHEN 1 THEN 'Monday'
        WHEN 2 THEN 'Tuesday'
        WHEN 3 THEN 'Wednesday'
        WHEN 4 THEN 'Thursday'
        WHEN 5 THEN 'Friday'
        WHEN 6 THEN 'Saturday'
        WHEN 7 THEN 'Sunday'
        ELSE NULL
      END
    $$;

    CREATE TABLE app_users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      password_hash TEXT NOT NULL,
      role VARCHAR(32) NOT NULL CHECK (role IN ('superadmin', 'admin', 'doctor', 'receptionist')),
      status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE UNIQUE INDEX app_users_username_unique ON app_users (LOWER(username));
    CREATE UNIQUE INDEX app_users_email_unique ON app_users (LOWER(email));
    CREATE INDEX app_users_role_idx ON app_users (role);
    CREATE INDEX app_users_status_idx ON app_users (status);

    CREATE TABLE companies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL,
      contact VARCHAR(20) NOT NULL,
      registration_number VARCHAR(50) NOT NULL,
      address TEXT NOT NULL,
      subscription_plan VARCHAR(64),
      status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT companies_subscription_plan_check CHECK (
        subscription_plan IS NULL
        OR subscription_plan IN ('purchase', 'rental', 'per_consultation_with_doctor', 'per_consultation_without_doctor')
      )
    );

    CREATE UNIQUE INDEX companies_email_unique ON companies (LOWER(email));
    CREATE UNIQUE INDEX companies_registration_number_unique ON companies (registration_number);
    CREATE INDEX companies_status_idx ON companies (status);

    CREATE TABLE regions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      province VARCHAR(100) NOT NULL,
      sub_region VARCHAR(150) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT regions_province_sub_region_unique UNIQUE (province, sub_region)
    );

    CREATE TABLE cities (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      region_id BIGINT NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
      name VARCHAR(100) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT cities_name_region_unique UNIQUE (name, region_id)
    );

    CREATE INDEX cities_region_idx ON cities (region_id);
    CREATE INDEX cities_name_idx ON cities (LOWER(name));

    CREATE TABLE clinics (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      city_id BIGINT NOT NULL REFERENCES cities(id) ON DELETE RESTRICT,
      name VARCHAR(255) NOT NULL,
      location VARCHAR(255) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
      operating_hours JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX clinics_company_idx ON clinics (company_id);
    CREATE INDEX clinics_city_idx ON clinics (city_id);
    CREATE INDEX clinics_status_idx ON clinics (status);

    CREATE TABLE clinic_operating_hours (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      clinic_id BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
      day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
      open_time TIME NOT NULL,
      close_time TIME NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT clinic_operating_hours_clinic_day_unique UNIQUE (clinic_id, day_of_week)
    );

    CREATE TABLE specializations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(255) NOT NULL UNIQUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE superadmins (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id) ON DELETE CASCADE,
      name VARCHAR(255) NOT NULL,
      contact VARCHAR(20) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE admins (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id) ON DELETE CASCADE,
      company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      name VARCHAR(255) NOT NULL,
      contact VARCHAR(20) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX admins_company_idx ON admins (company_id);

    CREATE TABLE admin_regions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_id BIGINT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
      region_id BIGINT NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT admin_regions_admin_region_unique UNIQUE (admin_id, region_id)
    );

    CREATE INDEX admin_regions_admin_idx ON admin_regions (admin_id);
    CREATE INDEX admin_regions_region_idx ON admin_regions (region_id);

    CREATE TABLE receptionists (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id) ON DELETE CASCADE,
      clinic_id BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
      name VARCHAR(255) NOT NULL,
      contact VARCHAR(20) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX receptionists_clinic_idx ON receptionists (clinic_id);
    CREATE INDEX receptionists_status_idx ON receptionists (status);

    CREATE TABLE doctors (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id) ON DELETE CASCADE,
      clinic_id BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
      name VARCHAR(255) NOT NULL,
      specialization_id BIGINT REFERENCES specializations(id) ON DELETE SET NULL,
      license_number VARCHAR(100) NOT NULL UNIQUE,
      contact VARCHAR(20) NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
      missed_shifts_count INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX doctors_clinic_idx ON doctors (clinic_id);
    CREATE INDEX doctors_status_idx ON doctors (status);
    CREATE INDEX doctors_specialization_idx ON doctors (specialization_id);

    CREATE TABLE doctor_weekly_availability (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      doctor_id BIGINT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
      day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
      start_time TIME,
      end_time TIME,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT doctor_weekly_availability_doctor_day_unique UNIQUE (doctor_id, day_of_week)
    );

    CREATE INDEX doctor_weekly_availability_doctor_idx ON doctor_weekly_availability (doctor_id);
    CREATE INDEX doctor_weekly_availability_day_idx ON doctor_weekly_availability (day_of_week);

    CREATE TABLE patients (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(255) NOT NULL,
      age INTEGER NOT NULL CHECK (age BETWEEN 0 AND 150),
      gender VARCHAR(20) NOT NULL CHECK (gender IN ('Male', 'Female')),
      father_name VARCHAR(255) NOT NULL,
      marital_status VARCHAR(20) NOT NULL CHECK (marital_status IN ('Married', 'Single')),
      contact VARCHAR(20) NOT NULL,
      email VARCHAR(255) NOT NULL,
      address VARCHAR(255) NOT NULL,
      cnic VARCHAR(15) NOT NULL CHECK (cnic ~ '^\\d{5}-\\d{7}-\\d$'),
      occupation VARCHAR(255),
      nationality VARCHAR(255) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE UNIQUE INDEX patients_cnic_unique ON patients (cnic);
    CREATE INDEX patients_contact_idx ON patients (contact);
    CREATE INDEX patients_email_idx ON patients (LOWER(email));
    CREATE INDEX patients_name_idx ON patients (LOWER(name));

    CREATE TABLE appointments_core (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
      doctor_id BIGINT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
      clinic_id BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
      ticket_no INTEGER NOT NULL,
      scheduled_for TIMESTAMPTZ,
      queue_date DATE NOT NULL DEFAULT CURRENT_DATE,
      status VARCHAR(20) NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting', 'completed', 'cancelled')),
      started_at TIMESTAMPTZ,
      ended_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT appointments_core_ticket_unique UNIQUE (clinic_id, queue_date, ticket_no)
    );

    CREATE INDEX appointments_core_patient_idx ON appointments_core (patient_id);
    CREATE INDEX appointments_core_doctor_idx ON appointments_core (doctor_id);
    CREATE INDEX appointments_core_clinic_idx ON appointments_core (clinic_id);
    CREATE INDEX appointments_core_status_idx ON appointments_core (status);
    CREATE INDEX appointments_core_created_at_idx ON appointments_core (created_at DESC);

    CREATE TABLE appointment_encounters (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments_core(id) ON DELETE CASCADE,
      vitals JSONB NOT NULL DEFAULT '{}'::jsonb,
      diagnosis TEXT NOT NULL DEFAULT '',
      prescription TEXT NOT NULL DEFAULT '',
      notes TEXT NOT NULL DEFAULT '',
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE doctor_unavailability_requests (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      doctor_id BIGINT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
      clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE,
      start_datetime TIMESTAMPTZ NOT NULL,
      end_datetime TIMESTAMPTZ NOT NULL,
      reason TEXT NOT NULL DEFAULT '',
      status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
      admin_reviewer_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
      admin_comment TEXT,
      receptionist_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (receptionist_status IN ('pending', 'forwarded')),
      receptionist_comment TEXT,
      receptionist_id BIGINT REFERENCES receptionists(id) ON DELETE SET NULL,
      forwarded_to_admin_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT doctor_unavailability_requests_date_range_check CHECK (end_datetime > start_datetime)
    );

    CREATE INDEX doctor_unavailability_requests_doctor_idx ON doctor_unavailability_requests (doctor_id);
    CREATE INDEX doctor_unavailability_requests_status_idx ON doctor_unavailability_requests (status);
    CREATE INDEX doctor_unavailability_requests_clinic_idx ON doctor_unavailability_requests (clinic_id);

    CREATE TABLE doctor_region_change_requests (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      doctor_id BIGINT NOT NULL REFERENCES doctors(id) ON DELETE CASCADE,
      clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE,
      requested_region_id BIGINT NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
      status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
      admin_reviewer_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
      reason TEXT NOT NULL DEFAULT '',
      reviewer_comment TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX doctor_region_change_requests_doctor_idx ON doctor_region_change_requests (doctor_id);
    CREATE INDEX doctor_region_change_requests_region_idx ON doctor_region_change_requests (requested_region_id);

    CREATE TABLE bulletins (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
      title VARCHAR(255) NOT NULL,
      message TEXT NOT NULL,
      active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX bulletins_company_idx ON bulletins (company_id);
    CREATE INDEX bulletins_active_idx ON bulletins (active);

    CREATE TABLE admin_change_requests (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      admin_id BIGINT NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
      request_type VARCHAR(50) NOT NULL CHECK (request_type IN ('password_reset', 'contact_change', 'general_query')),
      requested_data TEXT NOT NULL,
      reason TEXT,
      status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
      rejection_reason TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX admin_change_requests_admin_idx ON admin_change_requests (admin_id);
    CREATE INDEX admin_change_requests_status_idx ON admin_change_requests (status);

    CREATE TABLE complaints (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      clinic_id BIGINT NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
      patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL,
      created_by_receptionist_id BIGINT REFERENCES receptionists(id) ON DELETE SET NULL,
      complaint_type VARCHAR(50) NOT NULL DEFAULT 'general',
      title VARCHAR(255) NOT NULL,
      description TEXT NOT NULL,
      status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
      resolution_note TEXT,
      resolved_by_role VARCHAR(20),
      resolved_by_receptionist_id BIGINT REFERENCES receptionists(id) ON DELETE SET NULL,
      resolved_by_admin_id BIGINT REFERENCES admins(id) ON DELETE SET NULL,
      escalated_to_admin BOOLEAN NOT NULL DEFAULT FALSE,
      escalated_at TIMESTAMPTZ,
      escalation_note TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX complaints_clinic_idx ON complaints (clinic_id);
    CREATE INDEX complaints_status_idx ON complaints (status);
    CREATE INDEX complaints_created_by_idx ON complaints (created_by_receptionist_id);

    CREATE TABLE notification_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type VARCHAR(100) NOT NULL,
      patient_id BIGINT REFERENCES patients(id) ON DELETE CASCADE,
      doctor_id BIGINT REFERENCES doctors(id) ON DELETE CASCADE,
      receptionist_id BIGINT REFERENCES receptionists(id) ON DELETE CASCADE,
      clinic_id BIGINT REFERENCES clinics(id) ON DELETE CASCADE,
      clinic_name VARCHAR(255),
      title VARCHAR(255) NOT NULL,
      message TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX notification_events_created_at_idx ON notification_events (created_at DESC);

    CREATE TABLE notification_recipients (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      notification_id BIGINT NOT NULL REFERENCES notification_events(id) ON DELETE CASCADE,
      recipient_type VARCHAR(20) NOT NULL CHECK (recipient_type IN ('superadmin', 'admin', 'doctor', 'receptionist')),
      recipient_id BIGINT,
      read BOOLEAN NOT NULL DEFAULT FALSE,
      read_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT notification_recipients_recipient_check CHECK (
        (recipient_type = 'superadmin' AND recipient_id IS NULL)
        OR (recipient_type <> 'superadmin' AND recipient_id IS NOT NULL)
      )
    );

    CREATE INDEX notification_recipients_recipient_idx ON notification_recipients (recipient_type, recipient_id);
    CREATE INDEX notification_recipients_read_idx ON notification_recipients (read);

    CREATE TABLE audit_events (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
      role VARCHAR(32) NOT NULL,
      event_type VARCHAR(100) NOT NULL,
      metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX audit_events_event_type_idx ON audit_events (event_type);
    CREATE INDEX audit_events_created_at_idx ON audit_events (created_at DESC);
    CREATE INDEX audit_events_role_idx ON audit_events (role);

    CREATE TRIGGER app_users_set_updated_at
    BEFORE UPDATE ON app_users
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER companies_set_updated_at
    BEFORE UPDATE ON companies
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER regions_set_updated_at
    BEFORE UPDATE ON regions
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER cities_set_updated_at
    BEFORE UPDATE ON cities
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER clinics_set_updated_at
    BEFORE UPDATE ON clinics
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER clinic_operating_hours_set_updated_at
    BEFORE UPDATE ON clinic_operating_hours
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER specializations_set_updated_at
    BEFORE UPDATE ON specializations
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER superadmins_set_updated_at
    BEFORE UPDATE ON superadmins
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER admins_set_updated_at
    BEFORE UPDATE ON admins
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER admin_regions_set_updated_at
    BEFORE UPDATE ON admin_regions
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER receptionists_set_updated_at
    BEFORE UPDATE ON receptionists
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER doctors_set_updated_at
    BEFORE UPDATE ON doctors
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER doctor_weekly_availability_set_updated_at
    BEFORE UPDATE ON doctor_weekly_availability
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER patients_set_updated_at
    BEFORE UPDATE ON patients
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER appointments_core_set_updated_at
    BEFORE UPDATE ON appointments_core
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER appointment_encounters_set_updated_at
    BEFORE UPDATE ON appointment_encounters
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER doctor_unavailability_requests_set_updated_at
    BEFORE UPDATE ON doctor_unavailability_requests
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER doctor_region_change_requests_set_updated_at
    BEFORE UPDATE ON doctor_region_change_requests
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER bulletins_set_updated_at
    BEFORE UPDATE ON bulletins
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER admin_change_requests_set_updated_at
    BEFORE UPDATE ON admin_change_requests
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER complaints_set_updated_at
    BEFORE UPDATE ON complaints
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE TRIGGER notification_recipients_set_updated_at
    BEFORE UPDATE ON notification_recipients
    FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();

    CREATE FUNCTION app_sync_clinic_hours_from_cache()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      hour_entry record;
      open_value text;
      close_value text;
    BEGIN
      DELETE FROM clinic_operating_hours WHERE clinic_id = NEW.id;

      IF NEW.operating_hours IS NULL THEN
        RETURN NEW;
      END IF;

      FOR hour_entry IN
        SELECT key, value
        FROM jsonb_each(NEW.operating_hours)
      LOOP
        open_value := COALESCE(hour_entry.value ->> 'open', '');
        close_value := COALESCE(hour_entry.value ->> 'close', '');

        IF open_value <> '' AND close_value <> '' THEN
          INSERT INTO clinic_operating_hours (clinic_id, day_of_week, open_time, close_time)
          VALUES (
            NEW.id,
            app_day_name_to_number(hour_entry.key),
            open_value::time,
            close_value::time
          );
        END IF;
      END LOOP;

      RETURN NEW;
    END;
    $$;

    CREATE TRIGGER clinics_sync_operating_hours
    AFTER INSERT OR UPDATE OF operating_hours ON clinics
    FOR EACH ROW EXECUTE FUNCTION app_sync_clinic_hours_from_cache();

    CREATE FUNCTION app_fill_doctor_request_clinic_id()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF NEW.clinic_id IS NULL THEN
        SELECT clinic_id INTO NEW.clinic_id
        FROM doctors
        WHERE id = NEW.doctor_id;
      END IF;

      RETURN NEW;
    END;
    $$;

    CREATE TRIGGER doctor_unavailability_requests_fill_clinic
    BEFORE INSERT ON doctor_unavailability_requests
    FOR EACH ROW EXECUTE FUNCTION app_fill_doctor_request_clinic_id();

    CREATE TRIGGER doctor_region_change_requests_fill_clinic
    BEFORE INSERT ON doctor_region_change_requests
    FOR EACH ROW EXECUTE FUNCTION app_fill_doctor_request_clinic_id();

    CREATE FUNCTION app_schedule_is_active(p_doctor_id BIGINT, p_day_of_week INTEGER, p_start TIME, p_end TIME)
    RETURNS boolean
    LANGUAGE sql
    STABLE
    AS $$
      SELECT
        p_start IS NOT NULL
        AND p_end IS NOT NULL
        AND p_day_of_week = CASE
          WHEN EXTRACT(DOW FROM CURRENT_TIMESTAMP)::INTEGER = 0 THEN 7
          ELSE EXTRACT(DOW FROM CURRENT_TIMESTAMP)::INTEGER
        END
        AND EXISTS (
          SELECT 1
          FROM doctors d
          WHERE d.id = p_doctor_id
            AND d.status = 'active'
        )
        AND NOT EXISTS (
          SELECT 1
          FROM doctor_unavailability_requests dur
          WHERE dur.doctor_id = p_doctor_id
            AND dur.status = 'approved'
            AND dur.start_datetime <= CURRENT_TIMESTAMP
            AND dur.end_datetime >= CURRENT_TIMESTAMP
        )
        AND (
          (p_start <= p_end AND CURRENT_TIME BETWEEN p_start AND p_end)
          OR
          (p_start > p_end AND (CURRENT_TIME >= p_start OR CURRENT_TIME <= p_end))
        )
    $$;

    CREATE VIEW users AS
    SELECT
      id,
      username,
      email,
      password_hash AS password,
      role,
      status,
      created_at,
      updated_at
    FROM app_users;

    CREATE FUNCTION users_view_write()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      saved_row app_users%ROWTYPE;
    BEGIN
      IF TG_OP = 'INSERT' THEN
        INSERT INTO app_users (username, email, password_hash, role, status)
        VALUES (
          NEW.username,
          LOWER(NEW.email),
          NEW.password,
          NEW.role,
          COALESCE(NEW.status, 'active')
        )
        RETURNING * INTO saved_row;

        NEW.id := saved_row.id;
        NEW.email := saved_row.email;
        NEW.password := saved_row.password_hash;
        NEW.status := saved_row.status;
        NEW.created_at := saved_row.created_at;
        NEW.updated_at := saved_row.updated_at;
        RETURN NEW;
      ELSIF TG_OP = 'UPDATE' THEN
        UPDATE app_users
        SET username = COALESCE(NEW.username, OLD.username),
            email = LOWER(COALESCE(NEW.email, OLD.email)),
            password_hash = COALESCE(NEW.password, OLD.password),
            role = COALESCE(NEW.role, OLD.role),
            status = COALESCE(NEW.status, OLD.status)
        WHERE id = OLD.id
        RETURNING * INTO saved_row;

        NEW.id := saved_row.id;
        NEW.username := saved_row.username;
        NEW.email := saved_row.email;
        NEW.password := saved_row.password_hash;
        NEW.role := saved_row.role;
        NEW.status := saved_row.status;
        NEW.created_at := saved_row.created_at;
        NEW.updated_at := saved_row.updated_at;
        RETURN NEW;
      ELSIF TG_OP = 'DELETE' THEN
        DELETE FROM app_users WHERE id = OLD.id;
        RETURN OLD;
      END IF;

      RETURN NULL;
    END;
    $$;

    CREATE TRIGGER users_view_write_trigger
    INSTEAD OF INSERT OR UPDATE OR DELETE ON users
    FOR EACH ROW EXECUTE FUNCTION users_view_write();

    CREATE VIEW availability_schedules AS
    SELECT
      dwa.id,
      dwa.doctor_id,
      dwa.day_of_week,
      dwa.start_time,
      dwa.end_time,
      app_schedule_is_active(dwa.doctor_id, dwa.day_of_week, dwa.start_time, dwa.end_time) AS is_active,
      dwa.created_at,
      dwa.updated_at
    FROM doctor_weekly_availability dwa;

    CREATE FUNCTION availability_schedules_view_write()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      saved_row doctor_weekly_availability%ROWTYPE;
    BEGIN
      IF TG_OP = 'INSERT' THEN
        INSERT INTO doctor_weekly_availability (doctor_id, day_of_week, start_time, end_time)
        VALUES (NEW.doctor_id, NEW.day_of_week, NEW.start_time, NEW.end_time)
        RETURNING * INTO saved_row;

        NEW.id := saved_row.id;
        NEW.created_at := saved_row.created_at;
        NEW.updated_at := saved_row.updated_at;
        RETURN NEW;
      ELSIF TG_OP = 'UPDATE' THEN
        UPDATE doctor_weekly_availability
        SET doctor_id = COALESCE(NEW.doctor_id, OLD.doctor_id),
            day_of_week = COALESCE(NEW.day_of_week, OLD.day_of_week),
            start_time = CASE
              WHEN NEW.start_time IS DISTINCT FROM OLD.start_time THEN NEW.start_time
              ELSE OLD.start_time
            END,
            end_time = CASE
              WHEN NEW.end_time IS DISTINCT FROM OLD.end_time THEN NEW.end_time
              ELSE OLD.end_time
            END
        WHERE id = OLD.id
        RETURNING * INTO saved_row;

        NEW.id := saved_row.id;
        NEW.doctor_id := saved_row.doctor_id;
        NEW.day_of_week := saved_row.day_of_week;
        NEW.start_time := saved_row.start_time;
        NEW.end_time := saved_row.end_time;
        NEW.created_at := saved_row.created_at;
        NEW.updated_at := saved_row.updated_at;
        NEW.is_active := app_schedule_is_active(saved_row.doctor_id, saved_row.day_of_week, saved_row.start_time, saved_row.end_time);
        RETURN NEW;
      ELSIF TG_OP = 'DELETE' THEN
        DELETE FROM doctor_weekly_availability WHERE id = OLD.id;
        RETURN OLD;
      END IF;

      RETURN NULL;
    END;
    $$;

    CREATE TRIGGER availability_schedules_view_write_trigger
    INSTEAD OF INSERT OR UPDATE OR DELETE ON availability_schedules
    FOR EACH ROW EXECUTE FUNCTION availability_schedules_view_write();

    CREATE VIEW appointments AS
    SELECT
      ac.id,
      ac.patient_id,
      ac.doctor_id,
      ac.clinic_id,
      ac.ticket_no,
      COALESCE(ae.vitals, '{}'::jsonb) AS vitals,
      COALESCE(ae.diagnosis, '') AS diagnosis,
      COALESCE(ae.prescription, '') AS prescription,
      COALESCE(ae.notes, '') AS notes,
      ac.status,
      ac.created_at,
      ac.started_at,
      ac.ended_at,
      ac.updated_at
    FROM appointments_core ac
    LEFT JOIN appointment_encounters ae ON ae.appointment_id = ac.id;

    CREATE FUNCTION appointments_view_write()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      saved_core appointments_core%ROWTYPE;
      saved_encounter appointment_encounters%ROWTYPE;
    BEGIN
      IF TG_OP = 'INSERT' THEN
        INSERT INTO appointments_core (patient_id, doctor_id, clinic_id, ticket_no, status, started_at, ended_at)
        VALUES (
          NEW.patient_id,
          NEW.doctor_id,
          NEW.clinic_id,
          NEW.ticket_no,
          COALESCE(NEW.status, 'waiting'),
          NEW.started_at,
          NEW.ended_at
        )
        RETURNING * INTO saved_core;

        INSERT INTO appointment_encounters (appointment_id, vitals, diagnosis, prescription, notes)
        VALUES (
          saved_core.id,
          COALESCE(NEW.vitals, '{}'::jsonb),
          COALESCE(NEW.diagnosis, ''),
          COALESCE(NEW.prescription, ''),
          COALESCE(NEW.notes, '')
        )
        RETURNING * INTO saved_encounter;

        NEW.id := saved_core.id;
        NEW.status := saved_core.status;
        NEW.created_at := saved_core.created_at;
        NEW.updated_at := saved_core.updated_at;
        NEW.vitals := saved_encounter.vitals;
        NEW.diagnosis := saved_encounter.diagnosis;
        NEW.prescription := saved_encounter.prescription;
        NEW.notes := saved_encounter.notes;
        RETURN NEW;
      ELSIF TG_OP = 'UPDATE' THEN
        UPDATE appointments_core
        SET patient_id = COALESCE(NEW.patient_id, OLD.patient_id),
            doctor_id = COALESCE(NEW.doctor_id, OLD.doctor_id),
            clinic_id = COALESCE(NEW.clinic_id, OLD.clinic_id),
            ticket_no = COALESCE(NEW.ticket_no, OLD.ticket_no),
            status = COALESCE(NEW.status, OLD.status),
            started_at = CASE
              WHEN NEW.started_at IS DISTINCT FROM OLD.started_at THEN NEW.started_at
              ELSE OLD.started_at
            END,
            ended_at = CASE
              WHEN NEW.ended_at IS DISTINCT FROM OLD.ended_at THEN NEW.ended_at
              ELSE OLD.ended_at
            END
        WHERE id = OLD.id
        RETURNING * INTO saved_core;

        INSERT INTO appointment_encounters (appointment_id, vitals, diagnosis, prescription, notes)
        VALUES (
          OLD.id,
          COALESCE(NEW.vitals, OLD.vitals, '{}'::jsonb),
          COALESCE(NEW.diagnosis, OLD.diagnosis, ''),
          COALESCE(NEW.prescription, OLD.prescription, ''),
          COALESCE(NEW.notes, OLD.notes, '')
        )
        ON CONFLICT (appointment_id)
        DO UPDATE SET
          vitals = EXCLUDED.vitals,
          diagnosis = EXCLUDED.diagnosis,
          prescription = EXCLUDED.prescription,
          notes = EXCLUDED.notes
        RETURNING * INTO saved_encounter;

        NEW.id := saved_core.id;
        NEW.patient_id := saved_core.patient_id;
        NEW.doctor_id := saved_core.doctor_id;
        NEW.clinic_id := saved_core.clinic_id;
        NEW.ticket_no := saved_core.ticket_no;
        NEW.status := saved_core.status;
        NEW.created_at := saved_core.created_at;
        NEW.started_at := saved_core.started_at;
        NEW.ended_at := saved_core.ended_at;
        NEW.updated_at := saved_core.updated_at;
        NEW.vitals := saved_encounter.vitals;
        NEW.diagnosis := saved_encounter.diagnosis;
        NEW.prescription := saved_encounter.prescription;
        NEW.notes := saved_encounter.notes;
        RETURN NEW;
      ELSIF TG_OP = 'DELETE' THEN
        DELETE FROM appointments_core WHERE id = OLD.id;
        RETURN OLD;
      END IF;

      RETURN NULL;
    END;
    $$;

    CREATE TRIGGER appointments_view_write_trigger
    INSTEAD OF INSERT OR UPDATE OR DELETE ON appointments
    FOR EACH ROW EXECUTE FUNCTION appointments_view_write();

    CREATE VIEW clinic_complaints AS
    SELECT
      c.id,
      c.clinic_id,
      c.patient_id,
      c.created_by_receptionist_id AS receptionist_id,
      c.complaint_type,
      c.title,
      c.description,
      c.status,
      c.resolution_note,
      c.created_at,
      c.updated_at,
      c.resolved_by_role,
      c.resolved_by_receptionist_id,
      c.escalated_to_admin,
      c.escalated_at,
      c.escalation_note
    FROM complaints c;

    CREATE FUNCTION clinic_complaints_view_write()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      saved_row complaints%ROWTYPE;
    BEGIN
      IF TG_OP = 'INSERT' THEN
        INSERT INTO complaints (
          clinic_id,
          patient_id,
          created_by_receptionist_id,
          complaint_type,
          title,
          description,
          status,
          resolution_note,
          resolved_by_role,
          resolved_by_receptionist_id,
          escalated_to_admin,
          escalated_at,
          escalation_note
        )
        VALUES (
          NEW.clinic_id,
          NEW.patient_id,
          NEW.receptionist_id,
          COALESCE(NEW.complaint_type, 'general'),
          NEW.title,
          NEW.description,
          COALESCE(NEW.status, 'open'),
          NEW.resolution_note,
          NEW.resolved_by_role,
          NEW.resolved_by_receptionist_id,
          COALESCE(NEW.escalated_to_admin, FALSE),
          NEW.escalated_at,
          NEW.escalation_note
        )
        RETURNING * INTO saved_row;
      ELSIF TG_OP = 'UPDATE' THEN
        UPDATE complaints
        SET clinic_id = COALESCE(NEW.clinic_id, OLD.clinic_id),
            patient_id = COALESCE(NEW.patient_id, OLD.patient_id),
            created_by_receptionist_id = COALESCE(NEW.receptionist_id, OLD.receptionist_id),
            complaint_type = COALESCE(NEW.complaint_type, OLD.complaint_type),
            title = COALESCE(NEW.title, OLD.title),
            description = COALESCE(NEW.description, OLD.description),
            status = COALESCE(NEW.status, OLD.status),
            resolution_note = CASE
              WHEN NEW.resolution_note IS DISTINCT FROM OLD.resolution_note THEN NEW.resolution_note
              ELSE OLD.resolution_note
            END,
            resolved_by_role = CASE
              WHEN NEW.resolved_by_role IS DISTINCT FROM OLD.resolved_by_role THEN NEW.resolved_by_role
              ELSE OLD.resolved_by_role
            END,
            resolved_by_receptionist_id = CASE
              WHEN NEW.resolved_by_receptionist_id IS DISTINCT FROM OLD.resolved_by_receptionist_id THEN NEW.resolved_by_receptionist_id
              ELSE OLD.resolved_by_receptionist_id
            END,
            resolved_by_admin_id = CASE
              WHEN COALESCE(NEW.resolved_by_role, OLD.resolved_by_role) = 'admin' THEN resolved_by_admin_id
              ELSE resolved_by_admin_id
            END,
            escalated_to_admin = COALESCE(NEW.escalated_to_admin, OLD.escalated_to_admin),
            escalated_at = CASE
              WHEN NEW.escalated_at IS DISTINCT FROM OLD.escalated_at THEN NEW.escalated_at
              ELSE OLD.escalated_at
            END,
            escalation_note = CASE
              WHEN NEW.escalation_note IS DISTINCT FROM OLD.escalation_note THEN NEW.escalation_note
              ELSE OLD.escalation_note
            END
        WHERE id = OLD.id
        RETURNING * INTO saved_row;
      ELSIF TG_OP = 'DELETE' THEN
        DELETE FROM complaints WHERE id = OLD.id;
        RETURN OLD;
      END IF;

      NEW.id := saved_row.id;
      NEW.clinic_id := saved_row.clinic_id;
      NEW.patient_id := saved_row.patient_id;
      NEW.receptionist_id := saved_row.created_by_receptionist_id;
      NEW.complaint_type := saved_row.complaint_type;
      NEW.title := saved_row.title;
      NEW.description := saved_row.description;
      NEW.status := saved_row.status;
      NEW.resolution_note := saved_row.resolution_note;
      NEW.created_at := saved_row.created_at;
      NEW.updated_at := saved_row.updated_at;
      NEW.resolved_by_role := saved_row.resolved_by_role;
      NEW.resolved_by_receptionist_id := saved_row.resolved_by_receptionist_id;
      NEW.escalated_to_admin := saved_row.escalated_to_admin;
      NEW.escalated_at := saved_row.escalated_at;
      NEW.escalation_note := saved_row.escalation_note;
      RETURN NEW;
    END;
    $$;

    CREATE TRIGGER clinic_complaints_view_write_trigger
    INSTEAD OF INSERT OR UPDATE OR DELETE ON clinic_complaints
    FOR EACH ROW EXECUTE FUNCTION clinic_complaints_view_write();

    CREATE VIEW login_audit AS
    SELECT
      id,
      user_id,
      role,
      created_at AS logged_in_at
    FROM audit_events
    WHERE event_type = 'login';

    CREATE FUNCTION login_audit_view_write()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      saved_row audit_events%ROWTYPE;
    BEGIN
      INSERT INTO audit_events (user_id, role, event_type, metadata, created_at)
      VALUES (
        NEW.user_id,
        NEW.role,
        'login',
        '{}'::jsonb,
        COALESCE(NEW.logged_in_at, CURRENT_TIMESTAMP)
      )
      RETURNING * INTO saved_row;

      NEW.id := saved_row.id;
      NEW.logged_in_at := saved_row.created_at;
      RETURN NEW;
    END;
    $$;

    CREATE TRIGGER login_audit_view_write_trigger
    INSTEAD OF INSERT ON login_audit
    FOR EACH ROW EXECUTE FUNCTION login_audit_view_write();

    CREATE VIEW notifications AS
    SELECT
      nr.id,
      ne.type,
      nr.recipient_type,
      nr.recipient_id,
      ne.patient_id,
      ne.doctor_id,
      ne.receptionist_id,
      ne.clinic_id,
      ne.clinic_name,
      ne.title,
      ne.message,
      nr.read,
      ne.created_at
    FROM notification_recipients nr
    JOIN notification_events ne ON ne.id = nr.notification_id;

    CREATE FUNCTION notifications_view_write()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      saved_event notification_events%ROWTYPE;
      saved_recipient notification_recipients%ROWTYPE;
    BEGIN
      IF TG_OP = 'INSERT' THEN
        INSERT INTO notification_events (
          type,
          patient_id,
          doctor_id,
          receptionist_id,
          clinic_id,
          clinic_name,
          title,
          message
        )
        VALUES (
          NEW.type,
          NEW.patient_id,
          NEW.doctor_id,
          NEW.receptionist_id,
          NEW.clinic_id,
          NEW.clinic_name,
          NEW.title,
          NEW.message
        )
        RETURNING * INTO saved_event;

        INSERT INTO notification_recipients (
          notification_id,
          recipient_type,
          recipient_id,
          read,
          read_at
        )
        VALUES (
          saved_event.id,
          NEW.recipient_type,
          NEW.recipient_id,
          COALESCE(NEW.read, FALSE),
          CASE WHEN COALESCE(NEW.read, FALSE) THEN CURRENT_TIMESTAMP ELSE NULL END
        )
        RETURNING * INTO saved_recipient;

        NEW.id := saved_recipient.id;
        NEW.created_at := saved_event.created_at;
        NEW.read := saved_recipient.read;
        RETURN NEW;
      ELSIF TG_OP = 'UPDATE' THEN
        UPDATE notification_recipients
        SET read = COALESCE(NEW.read, OLD.read),
            read_at = CASE
              WHEN COALESCE(NEW.read, OLD.read) THEN CURRENT_TIMESTAMP
              ELSE NULL
            END
        WHERE id = OLD.id
        RETURNING * INTO saved_recipient;

        NEW.id := saved_recipient.id;
        NEW.type := OLD.type;
        NEW.recipient_type := OLD.recipient_type;
        NEW.recipient_id := OLD.recipient_id;
        NEW.patient_id := OLD.patient_id;
        NEW.doctor_id := OLD.doctor_id;
        NEW.receptionist_id := OLD.receptionist_id;
        NEW.clinic_id := OLD.clinic_id;
        NEW.clinic_name := OLD.clinic_name;
        NEW.title := OLD.title;
        NEW.message := OLD.message;
        NEW.created_at := OLD.created_at;
        NEW.read := saved_recipient.read;
        RETURN NEW;
      ELSIF TG_OP = 'DELETE' THEN
        DELETE FROM notification_recipients WHERE id = OLD.id;
        RETURN OLD;
      END IF;

      RETURN NULL;
    END;
    $$;

    CREATE TRIGGER notifications_view_write_trigger
    INSTEAD OF INSERT OR UPDATE OR DELETE ON notifications
    FOR EACH ROW EXECUTE FUNCTION notifications_view_write();
  `);
};

exports.down = (pgm) => {
  pgm.sql(`
    DROP VIEW IF EXISTS notifications;
    DROP VIEW IF EXISTS login_audit;
    DROP VIEW IF EXISTS clinic_complaints;
    DROP VIEW IF EXISTS appointments;
    DROP VIEW IF EXISTS availability_schedules;
    DROP VIEW IF EXISTS users;

    DROP TABLE IF EXISTS audit_events CASCADE;
    DROP TABLE IF EXISTS notification_recipients CASCADE;
    DROP TABLE IF EXISTS notification_events CASCADE;
    DROP TABLE IF EXISTS complaints CASCADE;
    DROP TABLE IF EXISTS admin_change_requests CASCADE;
    DROP TABLE IF EXISTS bulletins CASCADE;
    DROP TABLE IF EXISTS doctor_region_change_requests CASCADE;
    DROP TABLE IF EXISTS doctor_unavailability_requests CASCADE;
    DROP TABLE IF EXISTS appointment_encounters CASCADE;
    DROP TABLE IF EXISTS appointments_core CASCADE;
    DROP TABLE IF EXISTS patients CASCADE;
    DROP TABLE IF EXISTS doctor_weekly_availability CASCADE;
    DROP TABLE IF EXISTS doctors CASCADE;
    DROP TABLE IF EXISTS receptionists CASCADE;
    DROP TABLE IF EXISTS admin_regions CASCADE;
    DROP TABLE IF EXISTS admins CASCADE;
    DROP TABLE IF EXISTS superadmins CASCADE;
    DROP TABLE IF EXISTS specializations CASCADE;
    DROP TABLE IF EXISTS clinic_operating_hours CASCADE;
    DROP TABLE IF EXISTS clinics CASCADE;
    DROP TABLE IF EXISTS cities CASCADE;
    DROP TABLE IF EXISTS regions CASCADE;
    DROP TABLE IF EXISTS companies CASCADE;
    DROP TABLE IF EXISTS app_users CASCADE;

    DROP FUNCTION IF EXISTS notifications_view_write();
    DROP FUNCTION IF EXISTS login_audit_view_write();
    DROP FUNCTION IF EXISTS clinic_complaints_view_write();
    DROP FUNCTION IF EXISTS appointments_view_write();
    DROP FUNCTION IF EXISTS availability_schedules_view_write();
    DROP FUNCTION IF EXISTS users_view_write();
    DROP FUNCTION IF EXISTS app_schedule_is_active(BIGINT, INTEGER, TIME, TIME);
    DROP FUNCTION IF EXISTS app_fill_doctor_request_clinic_id();
    DROP FUNCTION IF EXISTS app_sync_clinic_hours_from_cache();
    DROP FUNCTION IF EXISTS app_set_updated_at();
    DROP FUNCTION IF EXISTS app_day_name_to_number(text);
    DROP FUNCTION IF EXISTS app_day_number_to_name(integer);
  `);
};
